<a href="https://colab.research.google.com/github/Ivan8Garcia/data-science/blob/main/Pandas_I_O.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Aula 1-Leyendo archivos CSV**

**Importando archivos CSV**

In [ ]:
import pandas as pd

In [ ]:
datos= pd.read_csv("superstore_data.csv")

In [ ]:
datos.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [ ]:
datos_punto_coma= pd.read_csv("superstore_data_punto_coma.csv")

In [ ]:
datos_punto_coma.head()

Id;Year_Birth;Education;Marital_Status;Income;Kidhome;Teenhome;Dt_Customer;Recency;MntWines;MntFruits;MntMeatProducts;MntFishProducts;MntSweetProducts;MntGoldProds;NumDealsPurchases;NumWebPurchases;NumCatalogPurchases;NumStorePurchases;NumWebVisitsMonth;Response;Complain
0  1826;1970;Graduation;Divorced;84835;0;0;6/16/2...                                                                                                                                                                                                                             
1  1;1961;Graduation;Single;57091;0;0;6/15/2014;0...                                                                                                                                                                                                                             
2  10476;1958;Graduation;Married;67267;0;1;5/13/2...                                                                                                                                                                                                                             
3  1386;1967;Graduation;Together;32474;1;1;11/5/2...                                                                                                                                                                                                                             
4  5371;1989;Graduation;Single;21474;1;0;8/4/2014...

##**Parametros de la funcion read_csv**

In [ ]:
datos_punto_coma= pd.read_csv("superstore_data_punto_coma.csv", sep=";")

In [ ]:
datos_punto_coma.head()

Id  Year_Birth   Education Marital_Status   Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0   
1      1        1961  Graduation         Single  57091.0        0         0   
2  10476        1958  Graduation        Married  67267.0        0         1   
3   1386        1967  Graduation       Together  32474.0        1         1   
4   5371        1989  Graduation         Single  21474.0        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [ ]:
#ESTAMOS HACIENDO EJEMPLOS USANDO NUEVAS FUNCIONES COMO NROWS(nrows sirve para las filas)
datos_primeras_lineas= pd.read_csv("superstore_data.csv", nrows= 5)
datos_primeras_lineas

Id  Year_Birth   Education Marital_Status  Income  Kidhome  Teenhome  \
0   1826        1970  Graduation       Divorced   84835        0         0   
1      1        1961  Graduation         Single   57091        0         0   
2  10476        1958  Graduation        Married   67267        0         1   
3   1386        1967  Graduation       Together   32474        1         1   
4   5371        1989  Graduation         Single   21474        1         0   

  Dt_Customer  Recency  MntWines  ...  MntFishProducts  MntSweetProducts  \
0   6/16/2014        0       189  ...              111               189   
1   6/15/2014        0       464  ...                7                 0   
2   5/13/2014        0       134  ...               15                 2   
3   11/5/2014        0        10  ...                0                 0   
4    8/4/2014        0         6  ...               11                 0   

   MntGoldProds  NumDealsPurchases  NumWebPurchases  NumCatalogPurchases  \
0           218                  1                4                    4   
1            37                  1                7                    3   
2            30                  1                3                    2   
3             0                  1                1                    0   
4            34                  2                3                    1   

   NumStorePurchases  NumWebVisitsMonth  Response  Complain  
0                  6                  1         1         0  
1                  7                  5         1         0  
2                  5                  2         0         0  
3                  2                  7         0         0  
4                  2                  7         1         0  

[5 rows x 22 columns]

In [ ]:
#EJEMPLO USANDO "USECOLS" (sirve para las columnas)
datos_seleccion= pd.read_csv("superstore_data.csv", usecols=["Id","Year_Birth","Income"])
datos_seleccion

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [ ]:
#EXACTAMENTE LO MISMO DE LA CELDA ANTERIOR SOLO QUE USANDO EN VEZ DE NOMBRE DE LA COLUMNA, USAMOS SU POSICION
datos_seleccion= pd.read_csv("superstore_data.csv", usecols=[0,1,4])
datos_seleccion

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

##**Escribiendo archivos csv**

In [ ]:
#EL METODO DE EXPORTACION ES= ".to_csv"
#datos_selecccion lo vamos a guardar en un csv y se va a llamar "clientes_mercado"
datos_seleccion.to_csv("clientes_mercado.csv")

In [ ]:
#clientes_mercado es la variable en la que vamos a guardarla,despues, se lee el archivo con .read_csv y dentro el archivo que queremos leer
#se agregó una columna de mas porque no pusimos index=false
clientes_mercado = pd.read_csv("clientes_mercado.csv")
clientes_mercado

Unnamed: 0     Id  Year_Birth   Income
0              0   1826        1970  84835.0
1              1      1        1961  57091.0
2              2  10476        1958  67267.0
3              3   1386        1967  32474.0
4              4   5371        1989  21474.0
...          ...    ...         ...      ...
2235        2235  10142        1976  66476.0
2236        2236   5263        1977  31056.0
2237        2237     22        1976  46310.0
2238        2238    528        1978  65819.0
2239        2239   4070        1969  94871.0

[2240 rows x 4 columns]

In [ ]:
#eliminando la columna del index
#se cambió el nombre del ejemplo anterior que era clientes_mercado por datos_mercado para no confundirse

datos_seleccion.to_csv("datos_mercado.csv",index = False)

In [ ]:
#visualizando el dataframe sin la columna agregada del index
datos_mercado= pd.read_csv("datos_mercado.csv")
datos_mercado

Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

#**Aula 2-Leyendo archivos Excel**

##Importando Archivos EXCEL

In [ ]:
import pandas as pd

In [ ]:
archivo="emisiones_CO2.xlsx"

In [ ]:
datos_co2 = pd.read_excel(archivo)

In [ ]:
datos_co2.head()

País ISO 3166-1 alpha-3   Año  Total  Carbón  Aceite  Gas  Cemento  \
0  Afganistán                AFG  1750    0.0     NaN     NaN  NaN      NaN   
1  Afganistán                AFG  1751    0.0     NaN     NaN  NaN      NaN   
2  Afganistán                AFG  1752    0.0     NaN     NaN  NaN      NaN   
3  Afganistán                AFG  1753    0.0     NaN     NaN  NaN      NaN   
4  Afganistán                AFG  1754    0.0     NaN     NaN  NaN      NaN   

   Quema  Otros  Per Capita  
0    NaN    NaN         NaN  
1    NaN    NaN         NaN  
2    NaN    NaN         NaN  
3    NaN    NaN         NaN  
4    NaN    NaN         NaN

In [ ]:
pd.ExcelFile(archivo).sheet_names

['emisiones_C02', 'emisiones_percapita', 'fuentes']

##**Parametros de la funcion read_Excel**

In [ ]:
percapita =pd.read_excel(archivo, sheet_name="emisiones_percapita")

In [ ]:
percapita.tail()

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
63099  Global                WLD  2017  4749682.0  1908857.0  1610910.0   
63100  Global                WLD  2018  4792753.0  1919213.0  1596350.0   
63101  Global                WLD  2019  4775633.0  1896468.0  1589920.0   
63102  Global                WLD  2020  4497423.0  1807760.0  1427353.0   
63103  Global                WLD  2021  4693699.0  1893923.0  1496614.0   

             Gas   Cemento    Quema    Otros  
63099   940144.0  198416.0  51579.0  39776.0  
63100   979965.0  204225.0  53634.0  39366.0  
63101   984878.0  208309.0  56569.0  39490.0  
63102   963695.0  208844.0  51981.0  37789.0  
63103  1001585.0  211472.0  52663.0  37443.0

In [ ]:
percapita.sample(5)

País ISO 3166-1 alpha-3   Año       Total  \
4157                      Bahrein                BHR  1827         NaN   
61267                     Vietnam                VNM  1817         NaN   
14931                   Dinamarca                DNK  1993  11674983.0   
32054               Liechtenstein                LIE  1980         0.0   
19359  África Ecuatorial Francesa                NaN  1797         NaN   

          Carbón     Aceite        Gas   Cemento     Quema     Otros  
4157         NaN        NaN        NaN       NaN       NaN       NaN  
61267        NaN        NaN        NaN       NaN       NaN       NaN  
14931  5477998.0  4620489.0  1126564.0  232219.0  112060.0  105653.0  
32054        NaN        NaN        NaN       NaN       NaN       NaN  
19359        NaN        NaN        NaN       NaN       NaN       NaN

In [ ]:
#sheet_names lo usamos para seleccionar una hoja de excel en especifico que tiene nombre
fuentes =pd.read_excel(archivo, sheet_name="fuentes")

In [ ]:
fuentes.tail()

País ISO 3166-1 alpha-3   Año                                 Total  \
63099  Global                WLD  2017  CDIAC 2022, BP, and Sum of countries   
63100  Global                WLD  2018  CDIAC 2022, BP, and Sum of countries   
63101  Global                WLD  2019  CDIAC 2022, BP, and Sum of countries   
63102  Global                WLD  2020  CDIAC 2022, BP, and Sum of countries   
63103  Global                WLD  2021  CDIAC 2022, BP, and Sum of countries   

                  Carbón             Aceite                Gas        Cemento  \
63099  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63100  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63101  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63102  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63103  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   

                    Quema   Otros  \
63099  CDIAC 2022 and GCP  [NONE]   
63100  CDIAC 2022 and GCP  [NONE]   
63101  CDIAC 2022 and GCP  [NONE]   
63102  CDIAC 2022 and GCP  [NONE]   
63103  CDIAC 2022 and GCP  [NONE]   

                                              Per Capita  
63099  CDIAC 2022, BP, Sum of countries, and UN popul...  
63100  CDIAC 2022, BP, Sum of countries, and UN popul...  
63101  CDIAC 2022, BP, Sum of countries, and UN popul...  
63102  CDIAC 2022, BP, Sum of countries, and UN popul...  
63103  CDIAC 2022, BP, Sum of countries, and UN popul...

In [ ]:
#estamos aplicando un intervalo de columnas de la "A:D"
intervalo =pd.read_excel(archivo, sheet_name="emisiones_C02", usecols="A:D")

In [ ]:
intervalo

País ISO 3166-1 alpha-3   Año         Total
0      Afganistán                AFG  1750  0.000000e+00
1      Afganistán                AFG  1751  0.000000e+00
2      Afganistán                AFG  1752  0.000000e+00
3      Afganistán                AFG  1753  0.000000e+00
4      Afganistán                AFG  1754  0.000000e+00
...           ...                ...   ...           ...
63099      Global                WLD  2017  3.609674e+10
63100      Global                WLD  2018  3.682651e+10
63101      Global                WLD  2019  3.708256e+10
63102      Global                WLD  2020  3.526409e+10
63103      Global                WLD  2021  3.712385e+10

[63104 rows x 4 columns]

In [ ]:
#agregamos nrows para seleccionar filas
intervalo_2 =pd.read_excel(archivo, sheet_name="emisiones_C02", usecols="A:D",nrows=10)


In [ ]:
intervalo_2

País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

##**Escribiendo archivos Excel**

In [ ]:
intervalo.to_excel("co2_percapita.xlsx", index= False)

In [ ]:
pd.read_excel("co2_percapita.xlsx")

País ISO 3166-1 alpha-3   Año  Total
0  Afganistán                AFG  1750      0
1  Afganistán                AFG  1751      0
2  Afganistán                AFG  1752      0
3  Afganistán                AFG  1753      0
4  Afganistán                AFG  1754      0
5  Afganistán                AFG  1755      0
6  Afganistán                AFG  1756      0
7  Afganistán                AFG  1757      0
8  Afganistán                AFG  1758      0
9  Afganistán                AFG  1759      0

##**Leyendo datos de Google sheets**

link:https://docs.google.com/spreadsheets/d/1YWGgG6ylh9S4K8z0tdIYc1uh1Vzj4ZtvI7PUlEzFlmw/edit?usp=sharing

In [ ]:
url= https://docs.google.com/spreadsheets/d/1YWGgG6ylh9S4K8z0tdIYc1uh1Vzj4ZtvI7PUlEzFlmw/edit?usp=sharing

In [ ]:
#al final del url dice sheet,significa que abre la primer hoja y para especificar si queremos alguna otra hoja que no sea la primera se hará en la celda siguiente del dataframe
sheet_id = "1YWGgG6ylh9S4K8z0tdIYc1uh1Vzj4ZtvI7PUlEzFlmw"
url= f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

In [ ]:
datos_co2_sheets= pd.read_csv(url)

In [ ]:
datos_co2_sheets

País ISO 3166-1 alpha-3   Año           Total          Carbón  \
0      Afganistán                AFG  1750               0             NaN   
1      Afganistán                AFG  1751               0             NaN   
2      Afganistán                AFG  1752               0             NaN   
3      Afganistán                AFG  1753               0             NaN   
4      Afganistán                AFG  1754               0             NaN   
...           ...                ...   ...             ...             ...   
63099      Global                WLD  2017  36.096.739.276  14.506.973.805   
63100      Global                WLD  2018  36.826.506.600  14.746.830.688   
63101      Global                WLD  2019  37.082.558.969  14.725.978.025   
63102      Global                WLD  2020  35.264.085.734  14.174.564.010   
63103      Global                WLD  2021  37.123.850.352  14.979.598.083   

               Aceite            Gas        Cemento        Quema        Otros  \
0                 NaN            NaN            NaN          NaN          NaN   
1                 NaN            NaN            NaN          NaN          NaN   
2                 NaN            NaN            NaN          NaN          NaN   
3                 NaN            NaN            NaN          NaN          NaN   
4                 NaN            NaN            NaN          NaN          NaN   
...               ...            ...            ...          ...          ...   
63099  12.242.627.935  7.144.928.128  1.507.923.185  391.992.176  302.294.047   
63100  12.266.016.285  7.529.846.784  1.569.218.392  412.115.746  302.478.706   
63101  12.345.653.374  7.647.528.220  1.617.506.786  439.253.991  306.638.573   
63102  11.191.808.551  7.556.290.283  1.637.537.532  407.583.673  296.301.685   
63103  11.837.159.116  7.921.829.472  1.672.592.372  416.525.563  296.145.746   

      Per Capita  
0            NaN  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
...          ...  
63099  4.749.682  
63100  4.792.753  
63101  4.775.633  
63102  4.497.423  
63103  4.693.699  

[63104 rows x 11 columns]

In [ ]:
#especificando la hoja dos del archivo de excel y creando una nueva variable de url_percapita para no confundirse y saber que es la url de la hoja 2 de excel
sheet_id = "1YWGgG6ylh9S4K8z0tdIYc1uh1Vzj4ZtvI7PUlEzFlmw"
sheet_name = "emisiones_percapita"
url_percapita= f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
percapita_sheet = pd.read_csv(url_percapita)
percapita_sheet

País ISO 3166-1 alpha-3   Año      Total     Carbón     Aceite  \
0      Afganistán                AFG  1750        NaN        NaN        NaN   
1      Afganistán                AFG  1751        NaN        NaN        NaN   
2      Afganistán                AFG  1752        NaN        NaN        NaN   
3      Afganistán                AFG  1753        NaN        NaN        NaN   
4      Afganistán                AFG  1754        NaN        NaN        NaN   
...           ...                ...   ...        ...        ...        ...   
63099      Global                WLD  2017  4.749.682  1.908.857  1.610.910   
63100      Global                WLD  2018  4.792.753  1.919.213  1.596.350   
63101      Global                WLD  2019  4.775.633  1.896.468  1.589.920   
63102      Global                WLD  2020  4.497.423  1.807.760  1.427.353   
63103      Global                WLD  2021  4.693.699  1.893.923  1.496.614   

             Gas  Cemento   Quema   Otros  
0            NaN      NaN     NaN     NaN  
1            NaN      NaN     NaN     NaN  
2            NaN      NaN     NaN     NaN  
3            NaN      NaN     NaN     NaN  
4            NaN      NaN     NaN     NaN  
...          ...      ...     ...     ...  
63099    940.144  198.416  51.579  39.776  
63100    979.965  204.225  53.634  39.366  
63101    984.878  208.309  56.569  39.490  
63102    963.695  208.844  51.981  37.789  
63103  1.001.585  211.472  52.663  37.443  

[63104 rows x 10 columns]

In [ ]:
#especificando la hoja tres del archivo de excel y creando una nueva variable de url_fuentes para no confundirse y saber que es la url de la hoja 3 de excel
sheet_id = "1YWGgG6ylh9S4K8z0tdIYc1uh1Vzj4ZtvI7PUlEzFlmw"
sheet_name = "fuentes"
url_fuentes= f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}'

In [ ]:
#creando la nueva variable y en ella guardando el archivo a leer de la url_fuentes
fuentes_sheets= pd.read_csv(url_fuentes)
fuentes_sheets.head()

País ISO 3166-1 alpha-3   Año   Total  Carbón  Aceite     Gas  \
0  Afganistán                AFG  1750  [NONE]  [NONE]  [NONE]  [NONE]   
1  Afganistán                AFG  1751  [NONE]  [NONE]  [NONE]  [NONE]   
2  Afganistán                AFG  1752  [NONE]  [NONE]  [NONE]  [NONE]   
3  Afganistán                AFG  1753  [NONE]  [NONE]  [NONE]  [NONE]   
4  Afganistán                AFG  1754  [NONE]  [NONE]  [NONE]  [NONE]   

  Cemento   Quema   Otros Per Capita  
0  [NONE]  [NONE]  [NONE]     [NONE]  
1  [NONE]  [NONE]  [NONE]     [NONE]  
2  [NONE]  [NONE]  [NONE]     [NONE]  
3  [NONE]  [NONE]  [NONE]     [NONE]  
4  [NONE]  [NONE]  [NONE]     [NONE]

In [ ]:
fuentes_sheets.tail()

País ISO 3166-1 alpha-3   Año                                 Total  \
63099  Global                WLD  2017  CDIAC 2022, BP, and Sum of countries   
63100  Global                WLD  2018  CDIAC 2022, BP, and Sum of countries   
63101  Global                WLD  2019  CDIAC 2022, BP, and Sum of countries   
63102  Global                WLD  2020  CDIAC 2022, BP, and Sum of countries   
63103  Global                WLD  2021  CDIAC 2022, BP, and Sum of countries   

                  Carbón             Aceite                Gas        Cemento  \
63099  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63100  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63101  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63102  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   
63103  CDIAC 2022 and BP  CDIAC 2022 and BP  CDIAC 2022 and BP  Andrew cement   

                    Quema   Otros  \
63099  CDIAC 2022 and GCP  [NONE]   
63100  CDIAC 2022 and GCP  [NONE]   
63101  CDIAC 2022 and GCP  [NONE]   
63102  CDIAC 2022 and GCP  [NONE]   
63103  CDIAC 2022 and GCP  [NONE]   

                                              Per Capita  
63099  CDIAC 2022, BP, Sum of countries, and UN popul...  
63100  CDIAC 2022, BP, Sum of countries, and UN popul...  
63101  CDIAC 2022, BP, Sum of countries, and UN popul...  
63102  CDIAC 2022, BP, Sum of countries, and UN popul...  
63103  CDIAC 2022, BP, Sum of countries, and UN popul...

In [ ]:
fuentes_sheets.sample(8)

País ISO 3166-1 alpha-3   Año       Total      Carbón  \
27599            Japón                JPN  1877      [NONE]      [NONE]   
9552        Cabo Verde                CPV  1782      [NONE]      [NONE]   
51020       Eslovaquia                SVK  1906      [NONE]      [NONE]   
37477        Marruecos                MAR  1963  CDIAC 2022  CDIAC 2022   
61921            Yemen                YEM  1927      [NONE]      [NONE]   
11091  Isla De Navidad                CXR  1961      [NONE]      [NONE]   
55113            Siria                SYR  1919      [NONE]      [NONE]   
55206            Siria                SYR  2012  CDIAC 2022  CDIAC 2022   

           Aceite         Gas        Cemento       Quema   Otros  \
27599      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
9552       [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
51020      [NONE]      [NONE]  Andrew cement      [NONE]  [NONE]   
37477  CDIAC 2022  CDIAC 2022  Andrew cement  CDIAC 2022  [NONE]   
61921      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
11091      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
55113      [NONE]      [NONE]         [NONE]      [NONE]  [NONE]   
55206  CDIAC 2022  CDIAC 2022  Andrew cement        GGFR  [NONE]   

                         Per Capita  
27599                      Maddison  
9552                         [NONE]  
51020                        [NONE]  
37477  CDIAC 2022 and UN population  
61921                        [NONE]  
11091                        [NONE]  
55113                        [NONE]  
55206  CDIAC 2022 and UN population

#**Aula 3- Leyendo archivos JSON**

##**importando archivos JSON**

In [ ]:
import pandas as pd

In [ ]:
pd.read_json("pacientes.json")
datos_pacientes= pd.read_json("pacientes.json")

In [ ]:
# en este archivo (pacientes.json) no contiene infor anidada por eso es facil de leerse pero en el siguiente si hay info anidada
datos_pacientes



ID_paciente Enfermedad_corazon    IMC Fumador Consumo_alcohol AVC  \
0              0                 No  16.60      Sí              No  No   
1              1                 No  20.34      No              No  Sí   
2              2                 No  26.58      Sí              No  No   
3              3                 No  24.21      No              No  No   
4              4                 No  23.71      No              No  No   
..           ...                ...    ...     ...             ...  ..   
995          995                 No  28.29      Sí              No  No   
996          996                 No  25.69      Sí              No  No   
997          997                 Sí  26.99      No              No  No   
998          998                 No  44.29      No              No  No   
999          999                 No  25.83      No              No  No   

     Salud_fisica  Salud_mental Dificultad_caminar Sexo_biologico Rango_edad  \
0               3            30                 No       Femenino      55-59   
1               0             0                 No       Femenino     80 ó +   
2              20            30                 No      Masculino      65-69   
3               0             0                 No       Femenino      75-79   
4              28             0                 Sí       Femenino      40-44   
..            ...           ...                ...            ...        ...   
995            10            20                 No       Femenino      65-69   
996             0             0                 No       Femenino      75-79   
997             1             0                 No      Masculino      70-74   
998            30             0                 Sí       Femenino      70-74   
999             0             0                 No      Masculino      70-74   

       Raza Diabetes Actividad_fisica Salud_general  Horas_sueño Asma  \
0    Blanca       Sí               Sí     Muy buena            5   Sí   
1    Blanca       No               Sí     Muy buena            7   No   
2    Blanca       Sí               Sí     Razonable            8   Sí   
3    Blanca       No               No         Buena            6   No   
4    Blanca       No               Sí     Muy buena            8   No   
..      ...      ...              ...           ...          ...  ...   
995   Negra       Sí               Sí     Razonable            8   No   
996  Blanca       No               Sí     Excelente            8   No   
997  Blanca       No               Sí     Muy buena            8   No   
998  Blanca       Sí               No         Buena            6   Sí   
999   Negra       Sí               No     Excelente            7   No   

    Enfermedad_renal Cancer_piel  
0                 No          Sí  
1                 No          No  
2                 No          No  
3                 No          Sí  
4                 No          No  
..               ...         ...  
995               No          No  
996               No          No  
997               No          No  
998               No          No  
999               No          No  

[1000 rows x 19 columns]

In [ ]:
#aqui tenemos como se muestra en el dataframe la info anidada
datos_pacientes_2= pd.read_json("pacientes_2.json")

In [ ]:
datos_pacientes_2

Investigación   Año  \
0  Indicadores clave de enfermedades cardíacas  2020   
1  Indicadores clave de enfermedades cardíacas  2020   
2  Indicadores clave de enfermedades cardíacas  2020   

                                           Pacientes  
0  {'ID': '01', 'Rango_edad': '55-59', 'Sexo_biol...  
1  {'ID': '02', 'Rango_edad': '80 ó +', 'Sexo_bio...  
2  {'ID': '03', 'Rango_edad': '65-69', 'Sexo_biol...

##**Normalizando archivos JSON**

In [ ]:
#con normalizar se refiere a quitar todos los diccionarios dentro de diccionarios y puede acomodar todo en columnas
#entre corchetes se especifica la columna en donde se encuentra el problema, en este caso es la columna pacientes
df_normalizado= pd.json_normalize(datos_pacientes_2["Pacientes"])

In [ ]:
df_normalizado

ID Rango_edad Sexo_biologico    Raza    IMC Fumador Consumo_alcohol  \
0  01      55-59          Mujer  Blanca  16.60      Sí              No   
1  02     80 ó +          Mujer  Blanca  20.34      No              No   
2  03      65-69      Masculino  Blanca  26.58      Sí              No   

   Salud_física  Salud_mental Dificultad_caminar Actividad_física  \
0             3            30                 No               Sí   
1             0             0                 No               Sí   
2            20            30                 No               Sí   

  Salud_general  Horas_sueño                Problemas_salud  
0     Muy buena            5  [Diabetes, Asma, Cancer_piel]  
1     Muy buena            7                          [AVC]  
2     Muy buena            8               [Diabetes, Asma]

##**Escribiendo archivos JSON**

In [ ]:
df_normalizado.to_json("historico_pacientes_norm.json")

In [ ]:
pd.read_csv("historico_pacientes_norm.json")

#**Aula 4- Leyendo paginas en HTML, XML**

##**importando paginas web**

In [4]:
import pandas as pd


In [6]:
datos_html = pd.read_html("peliculas_wikipedia.html")

In [ ]:
datos_html

[       0                      1
 0   1998             100 Movies
 1   1999              100 Stars
 2   2000             100 Laughs
 3   2001            100 Thrills
 4   2002           100 Passions
 5   2003  100 Heroes & Villains
 6   2004              100 Songs
 7   2005       100 Movie Quotes
 8   2005              25 Scores
 9   2006             100 Cheers
 10  2006            25 Musicals
 11  2007   100 Movies (Updated)
 12  2008        AFI's 10 Top 10
 13   vte                    vte,
                             Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   

In [7]:
type(datos_html)

list

In [8]:
#hace referencia a que es una lista de 3 elementos, osea 3 tablas... len se usa para ver el tamaño
len(datos_html)

3

In [9]:
#la posicion que nos interesa es la de la segunda tabla, osea la posicion 2 pero de valor 1 ya que se empieza a contar desde 0
top_peliculas = datos_html[1]

In [10]:
#EN ESTA VARIABLE YA TENEMOS GUARDADA EL DATA FRAME
top_peliculas

Film  Release year              Director  \
0                   Citizen Kane          1941          Orson Welles   
1                     Casablanca          1942        Michael Curtiz   
2                  The Godfather          1972  Francis Ford Coppola   
3             Gone with the Wind          1939        Victor Fleming   
4             Lawrence of Arabia          1962            David Lean   
..                           ...           ...                   ...   
95                 The Searchers          1956             John Ford   
96              Bringing Up Baby          1938          Howard Hawks   
97                    Unforgiven          1992        Clint Eastwood   
98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
99           Yankee Doodle Dandy          1942        Michael Curtiz   

                      Production companies  Rank  
0                       RKO Radio Pictures     1  
1                    Warner Bros. Pictures     2  
2   Paramount Pictures, Alfran Productions     3  
3          Selznick International Pictures     4  
4                         Horizon Pictures     5  
..                                     ...   ...  
95                  C. V. Whitney Pictures    96  
96                      RKO Radio Pictures    97  
97                     The Malpaso Company    98  
98                       Columbia Pictures    99  
99                   Warner Bros. Pictures   100  

[100 rows x 5 columns]

##**Escribiendo archivos HTML**

In [11]:
#PARA PODER TRANSFORMAR A csv,excel,json,html,etc. SIEMPRE DEBE SER PRIMERO EL DATA FRAME, SI NO, NO SE PUEDE
top_peliculas.to_html("top_peliculas.html",index= False)

In [12]:
pd.read_html("top_peliculas.html")

[                            Film  Release year              Director  \
 0                   Citizen Kane          1941          Orson Welles   
 1                     Casablanca          1942        Michael Curtiz   
 2                  The Godfather          1972  Francis Ford Coppola   
 3             Gone with the Wind          1939        Victor Fleming   
 4             Lawrence of Arabia          1962            David Lean   
 ..                           ...           ...                   ...   
 95                 The Searchers          1956             John Ford   
 96              Bringing Up Baby          1938          Howard Hawks   
 97                    Unforgiven          1992        Clint Eastwood   
 98  Guess Who's Coming to Dinner          1967        Stanley Kramer   
 99           Yankee Doodle Dandy          1942        Michael Curtiz   
 
                       Production companies  Rank  
 0                       RKO Radio Pictures     1  
 1                

In [13]:

top_peliculas.to_csv("top_peliculas_1998.csv", index= False)

In [14]:
datos= pd.read_csv("top_peliculas_1998.csv")
datos.head()

Film  Release year              Director  \
0        Citizen Kane          1941          Orson Welles   
1          Casablanca          1942        Michael Curtiz   
2       The Godfather          1972  Francis Ford Coppola   
3  Gone with the Wind          1939        Victor Fleming   
4  Lawrence of Arabia          1962            David Lean   

                     Production companies  Rank  
0                      RKO Radio Pictures     1  
1                   Warner Bros. Pictures     2  
2  Paramount Pictures, Alfran Productions     3  
3         Selznick International Pictures     4  
4                        Horizon Pictures     5

##**Leyendo/Escrbiendo archivos xml**

In [15]:
import pandas as pd

In [16]:
datos_imdb= pd.read_xml("imdb_top_1000.xml")

In [17]:
datos_imdb.head(3)

index                                        Poster_Link  \
0      0  https://m.media-amazon.com/images/M/MV5BMDFkYT...   
1      1  https://m.media-amazon.com/images/M/MV5BM2MyNj...   
2      2  https://m.media-amazon.com/images/M/MV5BMTMxNT...   

               Series_Title Released_Year Certificate  Runtime  \
0  The Shawshank Redemption          1994           A  142 min   
1             The Godfather          1972           A  175 min   
2           The Dark Knight          2008          UA  152 min   

                  Genre  IMDB_Rating  \
0                 Drama          9.3   
1          Crime, Drama          9.2   
2  Action, Crime, Drama          9.0   

                                            Overview  Meta_score  \
0  Two imprisoned men bond over a number of years...        80.0   
1  An organized crime dynasty's aging patriarch t...       100.0   
2  When the menace known as the Joker wreaks havo...        84.0   

               Director           Star1           Star2          Star3  \
0        Frank Darabont     Tim Robbins  Morgan Freeman     Bob Gunton   
1  Francis Ford Coppola   Marlon Brando       Al Pacino     James Caan   
2     Christopher Nolan  Christian Bale    Heath Ledger  Aaron Eckhart   

            Star4  No_of_Votes        Gross  
0  William Sadler      2343110   28,341,469  
1    Diane Keaton      1620367  134,966,411  
2   Michael Caine      2303232  534,858,444

#**Aula 5 - Leyendo banco de datos**

##**creando un banco de satos local**

In [18]:
import sqlalchemy

In [19]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text

In [20]:
#ENGINE es nuestro motor SQL, las 3 diagonales son para almacenar en la memoria interna del COLAB
engine= create_engine("sqlite:///memory:")

##**escribiendo en un banco de datos**

In [21]:
import pandas as pd

In [22]:
archivo = "clientes_banco.csv"

In [23]:
datos= pd.read_csv(archivo)

In [ ]:
datos.head()

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0     5008804    32    Nivel superior  Relación-estable               2   
1     5008805    32    Nivel superior  Relación-estable               2   
2     5008806    58  Nivel intermedio            Casado               2   
3     5008808    52  Nivel intermedio           Soltero               1   
4     5008809    52  Nivel intermedio           Soltero               1   

  Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0           Empleado       Otro             12           427500.0   
1           Empleado       Otro             12           427500.0   
2           Empleado  Seguridad              3           112500.0   
3   Business Partner     Ventas              8           270000.0   
4   Business Partner     Ventas              8           270000.0   

   Tiene_carro                  Vivienda  
0            1    Departamento alquilado  
1            1    Departamento alquilado  
2            1  Casa/Departamento propio  
3            0  Casa/Departamento propio  
4            0  Casa/Departamento propio

In [24]:
datos.to_sql("clientes",engine, index= False)


63947

In [25]:
#COMO SABER SI REALMENTE CREÓ LA TABLA DENTRO DEL ENGINE, para ello usaremos la funcion INSPECT
inspector= inspect(engine)

In [26]:
#el metodo .get_tables_names(), es exclusivo de la funcion inspect
print(inspector.get_table_names())

['clientes']


##**Leyendo una consulta SQL**

In [27]:
# SELECT* significa seleccionar todo
query= "SELECT * FROM clientes WHERE Categoria_de_renta = 'Empleado' "

In [28]:
#todo el codigo lo guardamos en una varible llamada empleados, para leer el sql invocamos a la variable query de arriba y
# en esta version se agrega text para leerla, despues la conectamos a nuestro motor, que es engine.connect()
empleados = pd.read_sql(sql=text(query), con=engine.connect())

In [29]:
#comprobamos que es un DATAFRAME
type(empleados)

pandas.core.frame.DataFrame

In [30]:
#VISUALIZAMOS EL DATA FRAME de solo "empleados", invocandolo
empleados

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0         5008804    32    Nivel superior  Relación-estable             2.0   
1         5008805    32    Nivel superior  Relación-estable             2.0   
2         5008806    58  Nivel intermedio            Casado             2.0   
3         5008815    46    Nivel superior            Casado             2.0   
4         5112956    46    Nivel superior            Casado             2.0   
...           ...   ...               ...               ...             ...   
32332     5223222    54  Nivel intermedio            Casado             2.0   
32333     5223223    54  Nivel intermedio            Casado             2.0   
32334     5223224    54  Nivel intermedio            Casado             2.0   
32335     5223225    54  Nivel intermedio            Casado             2.0   
32336     5223226    54  Nivel intermedio            Casado             2.0   

      Categoria_de_renta     Ocupacion  Años_empleado  Rendimiento_anual  \
0               Empleado          Otro           12.0           427500.0   
1               Empleado          Otro           12.0           427500.0   
2               Empleado     Seguridad            3.0           112500.0   
3               Empleado  Contabilidad            2.0           270000.0   
4               Empleado  Contabilidad            2.0           270000.0   
...                  ...           ...            ...                ...   
32332           Empleado        Cocina            2.0           112500.0   
32333           Empleado        Cocina            2.0           112500.0   
32334           Empleado        Cocina            2.0           112500.0   
32335           Empleado        Cocina            2.0           112500.0   
32336           Empleado        Cocina            2.0           112500.0   

       Tiene_carro                  Vivienda  
0              1.0    Departamento alquilado  
1              1.0    Departamento alquilado  
2              1.0  Casa/Departamento propio  
3              1.0  Casa/Departamento propio  
4              1.0  Casa/Departamento propio  
...            ...                       ...  
32332          0.0  Casa/Departamento propio  
32333          0.0  Casa/Departamento propio  
32334          0.0  Casa/Departamento propio  
32335          0.0  Casa/Departamento propio  
32336          0.0  Casa/Departamento propio  

[32337 rows x 11 columns]

**generaremos una nueva tabla, empezando siempre de nuestro data frame, que se llama EMPLEADOS**

In [31]:
#aqui se creó una tabla nueva llamada empleados porque si usamos la palabra "clientes", estaremos borrando la base de datos original
empleados.to_sql("empleados", con=engine.connect(), index= False)

32337

In [32]:
pd.read_sql_table("empleados", con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0         5008804    32    Nivel superior  Relación-estable             2.0   
1         5008805    32    Nivel superior  Relación-estable             2.0   
2         5008806    58  Nivel intermedio            Casado             2.0   
3         5008815    46    Nivel superior            Casado             2.0   
4         5112956    46    Nivel superior            Casado             2.0   
...           ...   ...               ...               ...             ...   
32332     5223222    54  Nivel intermedio            Casado             2.0   
32333     5223223    54  Nivel intermedio            Casado             2.0   
32334     5223224    54  Nivel intermedio            Casado             2.0   
32335     5223225    54  Nivel intermedio            Casado             2.0   
32336     5223226    54  Nivel intermedio            Casado             2.0   

      Categoria_de_renta     Ocupacion  Años_empleado  Rendimiento_anual  \
0               Empleado          Otro           12.0           427500.0   
1               Empleado          Otro           12.0           427500.0   
2               Empleado     Seguridad            3.0           112500.0   
3               Empleado  Contabilidad            2.0           270000.0   
4               Empleado  Contabilidad            2.0           270000.0   
...                  ...           ...            ...                ...   
32332           Empleado        Cocina            2.0           112500.0   
32333           Empleado        Cocina            2.0           112500.0   
32334           Empleado        Cocina            2.0           112500.0   
32335           Empleado        Cocina            2.0           112500.0   
32336           Empleado        Cocina            2.0           112500.0   

       Tiene_carro                  Vivienda  
0              1.0    Departamento alquilado  
1              1.0    Departamento alquilado  
2              1.0  Casa/Departamento propio  
3              1.0  Casa/Departamento propio  
4              1.0  Casa/Departamento propio  
...            ...                       ...  
32332          0.0  Casa/Departamento propio  
32333          0.0  Casa/Departamento propio  
32334          0.0  Casa/Departamento propio  
32335          0.0  Casa/Departamento propio  
32336          0.0  Casa/Departamento propio  

[32337 rows x 11 columns]

SI QUISIERA FILTRAR LA INFORMACION HACEMOS LO SIGUIENTE

In [33]:
pd.read_sql_table("empleados", con=engine.connect(),columns=["ID_Cliente","Grado_estudio","Rendimiento_anual"])

ID_Cliente     Grado_estudio  Rendimiento_anual
0         5008804    Nivel superior           427500.0
1         5008805    Nivel superior           427500.0
2         5008806  Nivel intermedio           112500.0
3         5008815    Nivel superior           270000.0
4         5112956    Nivel superior           270000.0
...           ...               ...                ...
32332     5223222  Nivel intermedio           112500.0
32333     5223223  Nivel intermedio           112500.0
32334     5223224  Nivel intermedio           112500.0
32335     5223225  Nivel intermedio           112500.0
32336     5223226  Nivel intermedio           112500.0

[32337 rows x 3 columns]

##**Actualizando un bando de datos**

In [34]:
query = "SELECT * FROM clientes"

In [35]:
pd.read_sql(sql=text(query) ,con = engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0         5008804    32    Nivel superior  Relación-estable             2.0   
1         5008805    32    Nivel superior  Relación-estable             2.0   
2         5008806    58  Nivel intermedio            Casado             2.0   
3         5008808    52  Nivel intermedio           Soltero             1.0   
4         5008809    52  Nivel intermedio           Soltero             1.0   
...           ...   ...               ...               ...             ...   
63942     5223224    54  Nivel intermedio            Casado             2.0   
63943     5223225    54  Nivel intermedio            Casado             2.0   
63944     5223226    54  Nivel intermedio            Casado             2.0   
63945     5223227    52  Nivel intermedio           Soltero             1.0   
63946     5223229    52               Niv              None             NaN   

      Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0               Empleado       Otro           12.0           427500.0   
1               Empleado       Otro           12.0           427500.0   
2               Empleado  Seguridad            3.0           112500.0   
3       Business Partner     Ventas            8.0           270000.0   
4       Business Partner     Ventas            8.0           270000.0   
...                  ...        ...            ...                ...   
63942           Empleado     Cocina            2.0           112500.0   
63943           Empleado     Cocina            2.0           112500.0   
63944           Empleado     Cocina            2.0           112500.0   
63945        Pensionista       Otro            0.0            90000.0   
63946               None       None            NaN                NaN   

       Tiene_carro                  Vivienda  
0              1.0    Departamento alquilado  
1              1.0    Departamento alquilado  
2              1.0  Casa/Departamento propio  
3              0.0  Casa/Departamento propio  
4              0.0  Casa/Departamento propio  
...            ...                       ...  
63942          0.0  Casa/Departamento propio  
63943          0.0  Casa/Departamento propio  
63944          0.0  Casa/Departamento propio  
63945          0.0  Casa/Departamento propio  
63946          NaN                      None  

[63947 rows x 11 columns]

In [36]:
#COMO BORRAR UN DATO DE LA BASE DE DATOS, borraremos el primer dato con ID_Cliente=5008804
from sqlalchemy.exc import SQLAlchemyError
query= "DELETE FROM clientes WHERE ID_Cliente = 5008804"
try:
  r_set= engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#registros borrados: ", r_set.rowcount)

#registros borrados:  1


In [37]:
pd.read_sql_table("clientes", con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0         5008804    32    Nivel superior  Relación-estable             2.0   
1         5008805    32    Nivel superior  Relación-estable             2.0   
2         5008806    58  Nivel intermedio            Casado             2.0   
3         5008808    52  Nivel intermedio           Soltero             1.0   
4         5008809    52  Nivel intermedio           Soltero             1.0   
...           ...   ...               ...               ...             ...   
63942     5223224    54  Nivel intermedio            Casado             2.0   
63943     5223225    54  Nivel intermedio            Casado             2.0   
63944     5223226    54  Nivel intermedio            Casado             2.0   
63945     5223227    52  Nivel intermedio           Soltero             1.0   
63946     5223229    52               Niv              None             NaN   

      Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0               Empleado       Otro           12.0           427500.0   
1               Empleado       Otro           12.0           427500.0   
2               Empleado  Seguridad            3.0           112500.0   
3       Business Partner     Ventas            8.0           270000.0   
4       Business Partner     Ventas            8.0           270000.0   
...                  ...        ...            ...                ...   
63942           Empleado     Cocina            2.0           112500.0   
63943           Empleado     Cocina            2.0           112500.0   
63944           Empleado     Cocina            2.0           112500.0   
63945        Pensionista       Otro            0.0            90000.0   
63946               None       None            NaN                NaN   

       Tiene_carro                  Vivienda  
0              1.0    Departamento alquilado  
1              1.0    Departamento alquilado  
2              1.0  Casa/Departamento propio  
3              0.0  Casa/Departamento propio  
4              0.0  Casa/Departamento propio  
...            ...                       ...  
63942          0.0  Casa/Departamento propio  
63943          0.0  Casa/Departamento propio  
63944          0.0  Casa/Departamento propio  
63945          0.0  Casa/Departamento propio  
63946          NaN                      None  

[63947 rows x 11 columns]

In [40]:
#COMO ACTUALIZAR UN VALOR O TEXTO DE LA TABLA
query= "UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente = 5008806"
try:
  r_set= engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros Actualizados: ", r_set.rowcount)

(sqlite3.OperationalError) database is locked
[SQL: UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente = 5008806]
(Background on this error at: https://sqlalche.me/e/20/e3q8)


In [41]:
pd.read_sql_table("clientes", con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0         5008804    32    Nivel superior  Relación-estable             2.0   
1         5008805    32    Nivel superior  Relación-estable             2.0   
2         5008806    58  Nivel intermedio            Casado             2.0   
3         5008808    52  Nivel intermedio           Soltero             1.0   
4         5008809    52  Nivel intermedio           Soltero             1.0   
...           ...   ...               ...               ...             ...   
63942     5223224    54  Nivel intermedio            Casado             2.0   
63943     5223225    54  Nivel intermedio            Casado             2.0   
63944     5223226    54  Nivel intermedio            Casado             2.0   
63945     5223227    52  Nivel intermedio           Soltero             1.0   
63946     5223229    52               Niv              None             NaN   

      Categoria_de_renta  Ocupacion  Años_empleado  Rendimiento_anual  \
0               Empleado       Otro           12.0           427500.0   
1               Empleado       Otro           12.0           427500.0   
2               Empleado  Seguridad            3.0           112500.0   
3       Business Partner     Ventas            8.0           270000.0   
4       Business Partner     Ventas            8.0           270000.0   
...                  ...        ...            ...                ...   
63942           Empleado     Cocina            2.0           112500.0   
63943           Empleado     Cocina            2.0           112500.0   
63944           Empleado     Cocina            2.0           112500.0   
63945        Pensionista       Otro            0.0            90000.0   
63946               None       None            NaN                NaN   

       Tiene_carro                  Vivienda  
0              1.0    Departamento alquilado  
1              1.0    Departamento alquilado  
2              1.0  Casa/Departamento propio  
3              0.0  Casa/Departamento propio  
4              0.0  Casa/Departamento propio  
...            ...                       ...  
63942          0.0  Casa/Departamento propio  
63943          0.0  Casa/Departamento propio  
63944          0.0  Casa/Departamento propio  
63945          0.0  Casa/Departamento propio  
63946          NaN                      None  

[63947 rows x 11 columns]

In [44]:
inspector= inspect(engine)
print(inspector.get_table_names())

['clientes', 'empleados']


#**PRIMER EJERCICIO**

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Disponemos de un archivo en formato CSV, el cual se obtuvo de la página Información de Salud (TABNET) - DATASUS. Este archivo contiene los gastos hospitalarios públicos de cada una de las Unidades de la Federación Brasileña desde enero de 2008 hasta marzo de 2021.

Su desafío aquí será leer este archivo usando la función read_csv de la biblioteca Pandas. Se deben agregar algunos parámetros para que la lectura se realice correctamente. Entonces, aquí hay algunos consejos:

1.Asegúrese de que el archivo CSV esté separado por una coma o punto y coma.

2.La codificación del archivo es ISO-8859-1.

3.Las primeras tres líneas del archivo se pueden ignorar, ya que el encabezado sólo comienza en la cuarta línea.

4.Las últimas 9 líneas también se pueden ignorar, ya que son sólo información sobre dónde se tomaron los datos.

5.Para eliminar las últimas líneas es necesario agregar el parámetro engine='python'.

Para leer el archivo podemos comenzar almacenando la dirección en una variable llamada url:

In [ ]:
url = 'datos_sus.csv'

Luego podemos leer la url con la función read_csv y agregar los parámetros:

encoding='ISO-8859-1': tipo de codificación de caracteres del archivo. En este caso, es la codificación ISO-8859-1 la que es común en los archivos en idioma portugués.

sep=';': separador de los valores del archivo. En este caso, es el punto y coma (;).

skiprows=3: indica que las primeras tres líneas del archivo deben ignorarse ya que no contienen datos relevantes.

skipfooter=9: Indica que las últimas nueve líneas del archivo deben ignorarse ya que no contienen datos relevantes.

engine='python': el motor utilizado para leer el archivo es Python.

Esto es necesario cuando se utiliza el parámetro skipfooter, ya que el motor predeterminado no admite esta opción.

In [ ]:
datos = pd.read_csv(url, encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter = 9, engine='python')

¡De esta manera los datos se cargarán exitosamente!

#**SEGUNDO EJERCICIO**

Es hora de que pongas a prueba los conocimientos desarrollados durante la clase. Tenemos un link de Google Sheets que contiene datos importantes sobre las emisiones de dióxido de carbono en todo el mundo. El conjunto de datos se obtuvo de Kaggle y consta de las emisiones de CO2 per cápita de todos los países del mundo entre 1990 y 2019.

En este desafío, tu función es leer este link de Google Sheets y luego guardar el DataFrame obtenido en formato CSV. ¿Listo para comenzar?

Iniciemos creando una variable que recibirá el ID de la hoja de trabajo.

¿Y dónde encontramos ese id? En el propio link. Es todo lo que aparece entre d/ y /edit.

In [ ]:
sheet_id = '1clj6rGaGlvZaLto2lgfFA7lodefC0OJgC86WgDm1nMU'

A continuación, creamos una variable que almacenará la dirección URL, pero podemos facilitar la escritura usando una f string para el sheet_id. Después de sheet_id tenemos algunos parámetros que se deben agregar.

En este primer momento es importante acceder a la API de visualización de datos de Google. Esto permitirá mostrar los datos de la hoja de cálculo de Google Sheets en Google Colab. Entonces, el parámetro **gviz/tq** indica que desea acceder a la función de consulta de datos de la API de visualización de datos.

La API también proporciona una forma de recuperar datos de hojas de cálculo como CSV, que es uno de los formatos que puede leer la biblioteca Pandas. Por este motivo indicamos el uso del parámetro **tqx=out:csv** para que los datos se devuelvan en formato CSV. El parámetro **sheet** recupera todos los datos de la hoja de trabajo, incluidos los encabezados de las columnas y las filas de datos.

In [ ]:
url = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet'

Una vez hecho esto, podemos leer los datos pasando la variable url a la función read_csv:

In [ ]:
datos = pd.read_csv(url)

Para guardar los datos en formato CSV, basta con utilizar la función to_csv y, entre paréntesis, darle un nombre al archivo agregando el parámetro index=False para que no se agregue una nueva columna de índice:

In [ ]:
datos.to_csv('datos_emisiones_co2.csv', index=False)

#**TERCER EJERCICIO**

Tenemos la siguiente situación-problema:

“Una empresa de alimentos saludables tiene problemas con la popularidad de sus productos. A pesar de ofrecer opciones saludables, muchos clientes se muestran reacios a comprar los productos debido a la falta de información sobre los valores nutricionales de las frutas que se utilizan en la producción de alimentos”.

Ante esta situación podemos acceder a una API llamada Fruitvice para recopilar información detallada sobre los valores nutricionales de las frutas que se utilizan en los productos. Con esta información, la empresa podrá actualizar sus empaques y materiales de marketing para resaltar los valores nutricionales de las frutas y así atraer más clientes que buscan opciones saludables. Además, la empresa puede utilizar la información para desarrollar nuevos productos que satisfagan aún más las necesidades nutricionales de su clientela.

Una forma común de acceder a las API es a través de la biblioteca requests. Para eso, también es necesario importar el módulo json:

Los datos de API Fruitvice se obtendrán con la función **request.get('url')**. Dentro de ella pasamos la dirección API seguida de **api/fruit/all** para obtener los datos de todas las frutas.

In [ ]:
import requests
import json

datos_frutas = requests.get('https://fruityvice.com/api/fruit/all')

Conseguimos recuperar los resultados utilizando la función **json.loads()**. Para ello es necesario pasar la variable **datos_frutas**, previamente creada con el atributo **text** que devuelve el contenido de la respuesta.

In [ ]:
resultado = json.loads(datos_frutas.text)

Luego podemos obtener una vista previa del DataFrame.

In [ ]:
import pandas as pd


In [ ]:
pd.DataFrame(resultado)


name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

                 

Para normalizar los datos necesitamos importar la biblioteca Pandas y podemos usar la función json_normalize:

In [ ]:
datos_frutas_normalizado = pd.json_normalize(resultado)

Comprobemos el DataFrame normalizado:

In [ ]:
datos_frutas_normalizado

name   id           family             order         genus  \
0            Persimmon   52        Ebenaceae           Rosales     Diospyros   
1           Strawberry    3         Rosaceae           Rosales      Fragaria   
2               Banana    1         Musaceae      Zingiberales          Musa   
3               Tomato    5       Solanaceae         Solanales       Solanum   
4                 Pear    4         Rosaceae           Rosales         Pyrus   
5               Durian   60        Malvaceae          Malvales         Durio   
6           Blackberry   64         Rosaceae           Rosales         Rubus   
7          Lingonberry   65        Ericaceae          Ericales     Vaccinium   
8                 Kiwi   66    Actinidiaceae  Struthioniformes       Apteryx   
9               Lychee   67      Sapindaceae        Sapindales        Litchi   
10           Pineapple   10     Bromeliaceae            Poales        Ananas   
11                 Fig   68         Moraceae           Rosales         Ficus   
12          Gooseberry   69  Grossulariaceae      Saxifragales         Ribes   
13        Passionfruit   70   Passifloraceae      Malpighiales    Passiflora   
14                Plum   71         Rosaceae           Rosales        Prunus   
15              Orange    2         Rutaceae        Sapindales        Citrus   
16          GreenApple   72         Rosaceae           Rosales         Malus   
17           Raspberry   23         Rosaceae           Rosales         Rubus   
18          Watermelon   25    Cucurbitaceae      Cucurbitales     Citrullus   
19               Lemon   26         Rutaceae        Sapindales        Citrus   
20               Mango   27    Anacardiaceae        Sapindales     Mangifera   
21           Blueberry   33         Rosaceae           Rosales      Fragaria   
22               Apple    6         Rosaceae           Rosales         Malus   
23               Guava   37        Myrtaceae          Myrtales       Psidium   
24             Apricot   35         Rosaceae           Rosales        Prunus   
25               Melon   41    Cucurbitaceae     Cucurbitaceae       Cucumis   
26           Tangerine   77         Rutaceae        Sapindales        Citrus   
27            Pitahaya   78        Cactaceae    Caryophyllales     Cactaceae   
28                Lime   44         Rutaceae        Sapindales        Citrus   
29         Pomegranate   79       Lythraceae          Myrtales        Punica   
30         Dragonfruit   80        Cactaceae    Caryophyllales  Selenicereus   
31               Grape   81         Vitaceae           Vitales         Vitis   
32               Morus   82         Moraceae           Rosales         Morus   
33              Feijoa   76        Myrtaceae        Myrtoideae    Sellowiana   
34             Avocado   84        Lauraceae          Laurales        Persea   
35           Kiwifruit   85    Actinidiaceae          Ericales     Actinidia   
36           Cranberry   87        Ericaceae          Ericales     Vaccinium   
37              Cherry    9         Rosaceae           Rosales        Prunus   
38               Peach   86         Rosaceae           Rosales        Prunus   
39           Jackfruit   94         Moraceae           Rosales    Artocarpus   
40        Horned Melon   95    Cucurbitaceae      Cucurbitales       Cucumis   
41            Hazelnut   96       Betulaceae           Fagales       Corylus   
42              Pomelo   98         Rutaceae        Sapindales        Citrus   
43          Mangosteen   99       Clusiaceae      Malpighiales      Garcinia   
44             Pumpkin  100    Cucurbitaceae      Cucurbitales     Cucurbita   
45  Japanese Persimmon  101        Ebenaceae          Ericales     Diospyros   
46              Papaya   42       Caricaceae       Brassicales        Carica   
47              Annona  103       Annonaceae           Rosales       Annonas   
48   Ceylon Gooseberry  104       Salicaceae      Malpighiales      Dovyalis   

    nutritions.ca

#**CUARTO EJERCICIO**

Vanessa es una científica de datos que está haciendo algunos análisis con datos ambientales. Está desarrollando un proyecto para evaluar el impacto ambiental de las actividades humanas en diferentes países del mundo, pero para ello necesita estimaciones de población de esos países. Al buscar en Internet, encontró una tabla de estimaciones de población en un artículo de la página de Wikipedia.

Al igual que Vanessa, tu desafío es obtener un DataFrame de la tabla que contiene la información del número de habitantes de cada país.

Para leer la página, simplemente pase la dirección a la función read_html. Para que se muestre la primera tabla asignamos el primer elemento de la lista, con [0]:

In [ ]:
import pandas as pd


In [ ]:
pd.read_html('https://es.wikipedia.org/wiki/Anexo:Pa%C3%ADses_y_territorios_dependientes_por_poblaci%C3%B3n')[0]

#**QUINTO EJERCICIO**

**SELECT** nombre, apellido, salario

**FROM** empleados

**WHERE** departamento = 'ventas'

En esta declaración SQL, la cláusula SELECT se utiliza para especificar las columnas que desea consultar de la tabla "empleados", incluyendo "nombre", "apellido" y "salario". La cláusula FROM se utiliza para especificar la tabla que se desea consultar, que en este caso es "empleados".

La cláusula WHERE se utiliza para filtrar los resultados de la consulta según una condición específica. En este ejemplo, la condición es departamento = 'ventas', lo que significa que la consulta solo devolverá empleados que trabajan en el departamento de ventas.

##**DESAFIO**

Usted es responsable de crear una base de datos local de clientes para una institución financiera. Disponemos del archivo CSV con los datos de los clientes.

Tu misión es:

1.Crear la base de datos local con la biblioteca **SQLAlchemy**.

2.Escribir los datos del archivo CSV en esta base de datos local.

3.Realizar tres actualizaciones en la base de datos:

*Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000.

*Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene cuenta en la institución financiera.

*Crear un nuevo registro de cliente siguiendo las especificaciones a continuación:

 ...  ID_cliente: 6850985

  ... Edad: 33

  ... Grado_estudio: Doctorado

 ...  Estado_civil: Soltero

  ... Tamaño_familia: 1

  ... Categoria_de_renta: Empleado

  ... Ocupacion: TI

  ... Años_empleado: 2

   ...Rendimiento_anual: 290000

  ... Tiene_carro: 0

   ...Vivienda: Casa/Departamento propio


**Consejo importante:** Para agregar un nuevo cliente a la tabla, use la cláusula **INSERT INTO** seguida del nombre de la tabla y luego especifique los nombres de las columnas de la tabla entre paréntesis. Utilice la cláusula **VALUES** y luego pase entre paréntesis los nuevos valores para este nuevo registro. Asegúrese de que los valores estén en el orden correcto y en el formato adecuado para cada columna.

**RESOLUCION DEL DESAFIO**

Para crear la base de datos local es necesario ejecutar los siguientes comandos. Este código consiste en importar la biblioteca **sqlalchemy** y crear un objeto engine que representa una conexión a una base de datos **SQLite** en memoria. El método **create_engine** se utiliza para crear el objeto engine y especificar la base de datos que se utilizará. En este caso, la base de datos es una base de datos SQLite en memoria, que se crea usando **sqlite:///:memory:**

In [45]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect, text
engine = create_engine('sqlite:///:memory:')

A continuación, podemos leer los datos con la función read_csv y escribirlos en el formato de la base de datos con la función to_sql:

In [46]:
import pandas as pd
archivo = 'clientes_banco.csv'
datos = pd.read_csv(archivo)
datos.to_sql('clientes', engine, index=False)

438463

Después de crear la tabla, podemos obtener un DataFrame con la función read_sql_table:



In [47]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           135000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

¡Ahora vamos a comenzar las actualizaciones de la base de datos!

Actualizar el registro del cliente ID 6840104 cuyo rendimiento anual cambió a 300000:

El siguiente código actualiza el rendimiento anual del ID de cliente 6840104 en la tabla **clientes**. La variable **query** contiene una declaración SQL que actualiza ese registro. Luego, la declaración **engine.connect()** se usa para crear una conexión a la base de datos SQLite. Finalmente, la declaración **.execute(text(query))** se utiliza para ejecutar la declaración SQL contenida en la variable **query** y actualizar el registro en la tabla **clientes**.

In [48]:
from sqlalchemy.exc import SQLAlchemyError
query = 'UPDATE clientes SET Rendimiento_anual=300000.0 WHERE ID_Cliente=6840104'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros actualizados: ",r_set.rowcount)

#Registros actualizados:  1


Después de ejecutar este código, puede verificar si la actualización realmente ocurrió leyendo la tabla "clientes"

In [49]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008809    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840104    62  Nivel intermedio        Divorciado               1   
438459     6840222    43  Nivel intermedio           Soltero               1   
438460     6841878    22    Nivel superior           Soltero               1   
438461     6842765    59  Nivel intermedio            Casado               2   
438462     6842885    51  Nivel intermedio            Casado               2   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458        Pensionista                Otro              0   
438459           Empleado  Construcción Civil              8   
438460   Business Partner              Ventas              1   
438461        Pensionista                Otro              0   
438462           Empleado              Ventas              3   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           300000.0            0  Casa/Departamento propio  
438459           103500.0            0  Casa/Departamento propio  
438460            54000.0            0       Vive con los padres  
438461            72000.0            0  Casa/Departamento propio  
438462           121500.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]

Eliminar el registro de cliente ID 5008809, ya que esta persona ya no tiene una cuenta en la institución financiera:

In [50]:
from sqlalchemy.exc import SQLAlchemyError
query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros borrados: ",r_set.rowcount)

#Registros borrados:  1


Cree un nuevo registro de cliente siguiendo las especificaciones dadas anteriormente:

Al trabajar con bases de datos, es común necesitar insertar nuevos registros en nuestras tablas. Para ello podemos utilizar la cláusula **INSERT INTO** que nos permite añadir nuevos datos de forma práctica y rápida.

Para utilizar esta cláusula, primero debe especificar el nombre de la tabla en la que se insertará el registro. A continuación, debemos pasar entre paréntesis los nombres de las columnas donde se agregarán los nuevos valores. **Es importante recordar que el orden de los nombres debe ser el mismo orden en el que se pasarán los valores.**

Después de especificar las columnas, usamos la cláusula **VALUES** para agregar los nuevos valores. Nuevamente debemos pasar entre paréntesis los valores a insertar en el mismo orden en que se especificaron las columnas. Es importante asegurarse de que los valores estén en el formato correcto para cada tipo de datos.

In [ ]:
#Como la `query` es larga, puedes usar `' \` para indicar que el código continúa en la siguiente línea.

In [51]:
from sqlalchemy.exc import SQLAlchemyError
query = 'INSERT INTO clientes (ID_Cliente, Edad, Grado_estudio, Estado_civil, ' \
        'Tamaño_familia, Categoria_de_renta, Ocupacion, Años_empleado, ' \
        'Rendimiento_anual, Tiene_carro, Vivienda) ' \
        'VALUES (6850985, 33, "Doctorado", "Soltero", 1, "Empleado", "TI", ' \
        '2, 290000, 0, "Casa/Departamento propio")'

try:
  r_set=engine.connect().execute(text(query))
except SQLAlchemyError as e:
  print(e)
else:
  print("#Registros insertados: ",r_set.rowcount)

#Registros insertados:  1


Para verificar que se realizaron los cambios, puede leer la tabla con el siguiente código:

In [52]:
pd.read_sql_table('clientes', con=engine.connect())

ID_Cliente  Edad     Grado_estudio      Estado_civil  Tamaño_familia  \
0          5008804    32    Nivel superior  Relación-estable               2   
1          5008805    32    Nivel superior  Relación-estable               2   
2          5008806    58  Nivel intermedio            Casado               2   
3          5008808    52  Nivel intermedio           Soltero               1   
4          5008810    52  Nivel intermedio           Soltero               1   
...            ...   ...               ...               ...             ...   
438458     6840222    43  Nivel intermedio           Soltero               1   
438459     6841878    22    Nivel superior           Soltero               1   
438460     6842765    59  Nivel intermedio            Casado               2   
438461     6842885    51  Nivel intermedio            Casado               2   
438462     6850985    33         Doctorado           Soltero               1   

       Categoria_de_renta           Ocupacion  Años_empleado  \
0                Empleado                Otro             12   
1                Empleado                Otro             12   
2                Empleado           Seguridad              3   
3        Business Partner              Ventas              8   
4        Business Partner              Ventas              8   
...                   ...                 ...            ...   
438458           Empleado  Construcción Civil              8   
438459   Business Partner              Ventas              1   
438460        Pensionista                Otro              0   
438461           Empleado              Ventas              3   
438462           Empleado                  TI              2   

        Rendimiento_anual  Tiene_carro                  Vivienda  
0                427500.0            1    Departamento alquilado  
1                427500.0            1    Departamento alquilado  
2                112500.0            1  Casa/Departamento propio  
3                270000.0            0  Casa/Departamento propio  
4                270000.0            0  Casa/Departamento propio  
...                   ...          ...                       ...  
438458           103500.0            0  Casa/Departamento propio  
438459            54000.0            0       Vive con los padres  
438460            72000.0            0  Casa/Departamento propio  
438461           121500.0            0  Casa/Departamento propio  
438462           290000.0            0  Casa/Departamento propio  

[438463 rows x 11 columns]